version: "3.2"
services:
  php:
    build: './PHP/'
    container_name: php
    networks:
      - backend
    ports:
      - 9000:9000
    volumes:
      - "./public_html:/var/www/html/:rw"
  apache:
    build: './Apache/'
    container_name: apache 
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "80:8080"
      - "3000:8080"
      - "443:443"
    volumes:
      - "./public_html:/var/www/html/:rw"
  db:
      image: mysql:5.6
      container_name: db 
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      networks:
        - backend
      environment:
         MYSQL_DATABASE: wpdb
         MYSQL_USER: localdbuser
         MYSQL_PASSWORD: rootpassword
         MYSQL_ROOT_PASSWORD: secret
  cli:
      image: wordpress:cli
      container_name: cli 
      user: root
      environment: 
        - APACHE_RUN_USER="www-data"
        - APACHE_RUN_GROUP="www-data"
      depends_on: 
        - db
      networks:
        - frontend
        - backend
      volumes:
        - "./public_html:/var/www/html/:rw"
networks:
  frontend:
  backend:  