version: "3.2"
services:
  php:
    build: './PHP/'
    networks:
      - backend
    ports:
      - 9000:9000
    volumes:
      - ./public_html/:/var/www/html 
  apache:
    build: './Apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:8080"
    volumes:
      - ./public_html/:/var/www/html 
  mysql:
      image: mysql:5.6.40
      networks:
        - backend
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend:  