version: "3.2"
services:
  php:
    build: './PHP/'
    networks:
      - backend
    ports:
      - 9000:9000
    volumes:
      - ./public_html/:/var/www/html 
  apache:
    build: './Apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:8080"
    volumes:
      - ./public_html/:/var/www/html 
  db:
      image: mysql:latest
      networks:
        - backend
      environment:
        - MYSQL_DATABASE=wpdb
        - MYSQL_USER=localdbuser
        - MYSQL_PASSWORD=rootpassword
        - MYSQL_ROOT_PASSWORD=secret
  cli:
      image: wordpress:cli
      volumes:
        - ./public_html:/var/www/html/
networks:
  frontend:
  backend:  